### PR TITLE
Update .hab-version to 0.85.0

### PR DESCRIPTION
**Pull request by afiune**
## Description
We have been using this version for a while now, this is an official bump so we
can get rid of the error message:
```
WARNING: Habitat version '0.85.0' is newer than the version of Habitat recommended for this project.
         Please consider exiting the studio, running:
         => hab studio rm
         to remove the studio, and then
         => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v 0.77.0
```

Signed-off-by: Salim Afiune <afiune@chef.io>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tduffield** [comment]
@afiune This file isn't really being used anymore. I thought y'all were using https://github.com/chef/studio-common for studio things now?

**Comment by afiune** [comment]
Yes, you are right. I opened a PR there, can we delete this file then to avoid confusion?

**Comment by tduffield** [comment]
@afiune I'm planning a major overhaul of this repo. I'll delete it as part of that. Right now I want to leave it be just in case its being used by other processes.

**Comment by afiune** [comment]
Carry-on! 👋

**Pull request closed without merging**
